networks:
  esi:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - esi

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "9000:9000" # Обязательно укажите порт, чтобы Nginx мог подключиться
    networks:
      - esi

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" # Убедитесь, что порт совпадает с тем, который используется в Nginx
    networks:
      - esi
