volumes:
  media: # Том для медиафайлов
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ./media # Локальная папка на хосте

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/var/www/media # Монтируем папку media
    depends_on:
      - backend
      - frontend
    networks:
      - esi

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - backend/.env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - ./mysql:/home
    networks:
      - esi

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "9000:9000"
    volumes:
      - ./media:/var/www/media # Монтируем ту же папку для доступа к медиафайлам
    networks:
      - esi

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - esi

networks:
  esi:
    driver: bridge
